// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & unknown> | ((props: { params: Promise<ParamMap[Route]> } & unknown) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<unknown[]> | unknown[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & unknown,
    parent: ResolvingMetadata
  ) => Promise<unknown> | unknown
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & unknown,
    parent: ResolvingViewport
  ) => Promise<unknown> | unknown
  metadata?: unknown
  viewport?: unknown
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<unknown[]> | unknown[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & unknown,
    parent: ResolvingMetadata
  ) => Promise<unknown> | unknown
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & unknown,
    parent: ResolvingViewport
  ) => Promise<unknown> | unknown
  metadata?: unknown
  viewport?: unknown
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("@/app/page.js")
  type __Check = __IsExpected<typeof handler>
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import('@/app/page.js')
  type __Check = __IsExpected<typeof handler>
  type __Unused = __Check
}
